# Dataset 2 - Lifestyle Weight Tracker
## Simple Linear Regression

In [2]:
# Importing the Library
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

In [3]:
# Load the Data
df = pd.read_csv("lifestyle weight tracker.csv")
df.head()

,User_ID,Age,Gender,Height_cm,Initial_Weight_kg,Stress_Level,Sleep_Hours,Caffeine_mg,Calories_Consumed,Protein_g,Carbs_g,Fat_g,Steps,Workout_Type,Workout_Intensity,Temp_C,Weight_Change,Current_Weight_kg
0,275,23,Female,169.355325,111.485330,10,7.016453,211.426469,2801.764291,175.1,315.2,93.4,8172,Strength,6,18.823955,0.317158,111.802488
1,296,43,Female,174.424939,109.699334,1,7.320227,211.979739,2666.001616,166.6,299.9,88.9,7988,NaN,0,36.987432,0.211877,109.911211
2,125,47,Male,163.246320,110.960286,3,7.238641,160.400067,1707.084012,106.7,192.0,56.9,7976,Yoga,10,35.977033,0.122390,111.082676
3,167,42,Female,164.997333,85.546097,7,5.060697,301.629856,2647.458547,165.5,297.8,88.2,8203,Cardio,10,33.141805,0.308449,85.854547
4,311,54,Male,167.696168,135.710505,5,9.866791,335.199126,2036.567163,127.3,229.1,67.9,8024,NaN,0,19.065076,0.120221,135.830726

In [11]:
# Check missing values
print(df.isnull().sum())

User_ID                 0
Age                     0
Gender                  0
Height_cm               0
Initial_Weight_kg       0
Stress_Level            0
Sleep_Hours             0
Caffeine_mg             0
Calories_Consumed    2750
Protein_g               0
Carbs_g                 0
Fat_g                   0
Steps                   0
Workout_Type            0
Workout_Intensity       0
Temp_C                  0
Weight_Change           0
Current_Weight_kg       0
dtype: int64

In [12]:
# Fill missing values with the column mean

df = df.fillna(df.mean(numeric_only=True))

In [4]:
# Encode categorical columns
le = LabelEncoder()

categorical_cols = ['Gender', 'Workout_Type', 'Workout_Intensity']

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

df.head()

,User_ID,Age,Gender,Height_cm,Initial_Weight_kg,Stress_Level,Sleep_Hours,Caffeine_mg,Calories_Consumed,Protein_g,Carbs_g,Fat_g,Steps,Workout_Type,Workout_Intensity,Temp_C,Weight_Change,Current_Weight_kg
0,275,23,0,169.355325,111.485330,10,7.016453,211.426469,2801.764291,175.1,315.2,93.4,8172,1,3,18.823955,0.317158,111.802488
1,296,43,0,174.424939,109.699334,1,7.320227,211.979739,2666.001616,166.6,299.9,88.9,7988,3,0,36.987432,0.211877,109.911211
2,125,47,1,163.246320,110.960286,3,7.238641,160.400067,1707.084012,106.7,192.0,56.9,7976,2,7,35.977033,0.122390,111.082676
3,167,42,0,164.997333,85.546097,7,5.060697,301.629856,2647.458547,165.5,297.8,88.2,8203,0,7,33.141805,0.308449,85.854547
4,311,54,1,167.696168,135.710505,5,9.866791,335.199126,2036.567163,127.3,229.1,67.9,8024,3,0,19.065076,0.120221,135.830726

# Simple Linear Regression

In [6]:
# Feature Selection
X = df[['Initial_Weight_kg']]
y = df['Current_Weight_kg']

In [7]:
# Split the Dataset

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [8]:
# Model Selection
model = LinearRegression()

In [9]:
# Fit the Model
model.fit(X_train, y_train)

LinearRegression()

In [10]:
print("Simple Linear Regression")
print("R2 Score:", r2_score(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))

Simple Linear Regression
R2 Score: 0.9003559324978518
MSE: 33.19435507203737

# Multiple Linear Regression

In [13]:
# Feature Selection
X = df.drop(columns=['User_ID','Current_Weight_kg'])
y = df['Current_Weight_kg']

In [14]:
# Split the Data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [15]:
# Model Selection
model = LinearRegression()

In [16]:
# Fit The Model
model.fit(X_train, y_train)

LinearRegression()

In [17]:
# Predict the Model
y_pred = model.predict(X_test)

In [18]:
print("Multiple Linear Regression")
print("R2 Score:", r2_score(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))

Multiple Linear Regression
R2 Score: 0.9003563631475333
MSE: 33.194211610025064